### ISSUE TITLE
Feature: Incorporate mse/eme youtube certification tests (2018)

### ISSUE THREAD

**Issue by igor-borovkov** [cta-wave/WMAS#35]
https://yt-dash-mse-test.commondatastorage.googleapis.com/unit-tests/2018.html?timestamp=1552412471123

https://github.com/youtube/js_mse_eme/tree/2018

Note: discussed prior with Mark Vickers as a feature request for WAVE test suite 2018

**Comment by squapp** [comment]
thanks, will forward to CTA WAVE for feedback
Are you / is your company member of CTA WAVE?

**Comment by igor-borovkov** [comment]
> thanks, will forward to CTA WAVE for feedback
> Are you / is your company member of CTA WAVE?

We work with Mark Vickers in the same company, we had a discussion recently after we started looking into WAVE test suite 2017, he encouraged us to file our suggestions for CTA WAVE test suite 2017 here to potentially include them into upcoming CTA WAVE test suite 2018.

**Comment by jpiesing** [comment]
This is not an objection to including these but ....
I looked at the list of tests and noticed that some of them may test "shall" statements that are not in the W3C MSE spec. For example, 20 on VideoBufferSize includes a comment that "tests that it meets the minimum requirements for streaming". What document are these in? 
WAVE has a long standing open issue on whether it needs to specify a minimum source buffer sizes - https://github.com/cta-wave/device-playback-task-force/issues/29 .

**Comment by mavgit** [comment]
Is this test suite updated on an annual or other regular basis? I'm wondering how those updates would synch up with our test suite updates.

**Comment by squapp** [comment]
yes, it has dedicated test cases for each year: https://ytlr-cert.appspot.com/links.html
Each year references a specific MSE/EME version, e.g. 
2018 conformance tests reference MSE Spec Version: 10 December 2013
2019 conformance tests reference MSE Spec Version: Current Editor's Draft

WMAS2018 on the other hand references MSE W3C Recommendation from 17 November 2016

If we were to integrate the YouTube Test Suite, we will need to make sure that the test cases are compliant with WMAS2018/2019

**Comment by jpiesing** [comment]
> If we were to integrate the YouTube Test Suite, we will need to make sure that the test cases are compliant with WMAS2018/2019

Can I repeat my previous observation that some of these tests appear to test additional YouTube requirements on MSE/EME and not requirements found in W3C or CTA WAVE. My preference would be to review those additional YouTube requirements & see if they should be included in CTA WAVE.

**Comment by jpiesing** [comment]
Looking at the source code for this, does it use the W3C test runner? I can't see any references to it.

**Comment by gitwjr** [comment]
Hi Jon, 

 

I am not sure if this is what you are looking for or not. I received this from Stefan Pham. I believe the second link is what you are talking about. Let me know if it is not. – Bill 

 

All of the included test files can be found here: https://github.com/cta-wave/WMAS/tree/wmas2018-tests

You could also check out https://github.com/cta-wave/WMAS/blob/wmas2018/wmats2018-subset.sh

This is the subsetting script, which pulls certain versions of test files from WPT, ECMAScript, WebGL etc.

Hope this helps

**Comment by jpiesing** [comment]
> Hi Jon, I am not sure if this is what you are looking for or not. I received this from Stefan Pham. I believe the second link is what you are talking about. Let me know if it is not. – Bill All of the included test files can be found here: https://github.com/cta-wave/WMAS/tree/wmas2018-tests You could also check out https://github.com/cta-wave/WMAS/blob/wmas2018/wmats2018-subset.sh This is the subsetting script, which pulls certain versions of test files from WPT, ECMAScript, WebGL etc. Hope this helps

Sorry Bill but that's not the point of the comment here. This issue is about the additional tests produced by YouTube for MSE/EME. When reviewing those tests, it looked to me like they don't use the W3C test runner.

**Comment by louaybassbouss** [comment]
@gitwjr I think @jpiesing asks if the YouTube test suite uses the WPT Test Runner. I think they use their own test runner. The integration in the WAVE Test Runner can be done similar to the integration of ECMAScript and WebGL tests in WMAS2018 Test Suite.

**Comment by mbergman42** [comment]
After working on all of these various feature requests (#35-#56) with MAV, our decision is to focus on the other feature requests and hold off on this item.  Development cost is likely high for this feature and the discussion here is inconclusive about the specificity of the tests, applicability of all elements to WAVE requirements.  

Suggest closing this item.  Happy to discuss further privately, but as far as issue tracking goes, this should be closed with no further action.

**Comment by jpiesing** [comment]
I agree that the elements may not be applicable to WAVE requirements but I think that could identify gaps in the WAVE requirements that should be investigated.
I don't completely agree with closing this item. I would prefer it be deferred or something similar if github has that kind of a status.

**Comment by squapp** [comment]
makes sense. I suggest to open an issue in HATF: https://github.com/cta-wave/HTML5-api-task-force/issues , since this a spec discussion
