### ISSUE TITLE
Feature: Tests: ability to blacklist / exclude certain tests (2018)

### ISSUE THREAD

**Issue by igor-borovkov** [cta-wave/WMAS#36]
For following cases:
- some tests might always cause a browser crash (or even a reboot) which is not fixable in short term (for example: a bug in a GPU driver in case of WebGL test cases if incorporated in the future)
- some tests might lead to a "permanent" hang / deadlock (for example, certain CSS tests lead to stalling / deadlocks when a browser uses a custom generated ICUDATA library)

*discussed prior with Mark Vickers as a potential feature for WAVE test suite 2018

**Comment by louaybassbouss** [comment]
If you run the test suite locally, you can already add tests to the exclude list available 
[/tools/wave/src/testing/test-loader.js#L65](/cta-wave/WMAS/blob/master/tools/wave/src/testing/test-loader.js#L65). On the hosted Test Runner, we need extend the runner to upload a list of excluded test files before starting a test session. This can be supported in future releases of the test suite.

**Comment by mbergman42** [comment]
Resolved.  We're opening a new work item to add this feature.  Expect the update available in mid Q4 2019. 
 Suggest closing this issue.
