### ISSUE TITLE
Feature: Report: show test files sorted by subdirectories (2018)

### ISSUE THREAD

**Issue by igor-borovkov** [cta-wave/WMAS#37]
**Example of a current list of test from a test report (HTML category):**
1. /html/webappapis/system-state-and-capabilities/the-navigator-object/navigator-indexed.html
2. /html/semantics/scripting-1/the-script-element/execution-timing/076.html
3. /html/rendering/replaced-elements/svg-embedded-sizing/svg-in-img-percentage.html
4. /html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-width.html
5. /html/semantics/embedded-content/the-canvas-element/security.drawImage.image.cross.html

**Expected after sorting**
1. /html/webappapis/system-state-and-capabilities/the-navigator-object/navigator-indexed.html
2. /html/semantics/embedded-content/the-canvas-element/security.drawImage.image.cross.html
3. /html/semantics/scripting-1/the-script-element/execution-timing/076.html
4. /html/rendering/replaced-elements/svg-embedded-sizing/svg-in-img-percentage.html
5. /html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-width.html

**Comment by louaybassbouss** [comment]
Similar to #38, this can be supported in future releases of the test suite.

**Comment by mbergman42** [comment]
Resolved.  We're opening a new work item to add this feature.  Expect the update available in mid Q4 2019. 
Suggest closing this issue.
