### ISSUE TITLE
Feature: Report: ability to sort test files by "status" (2018)

### ISSUE THREAD

**Issue by igor-borovkov** [cta-wave/WMAS#38]
Show all FAIL test files or test cases first in the list,  show all TIMEOUT test files next

**Comment by louaybassbouss** [comment]
This feature is not supported yet. Similar to #42, the [wptreport](https://github.com/w3c/wptreport) tool needs to be updated to sort the test files as you mentioned. This can be supported in future releases of the test suite.

**Comment by mbergman42** [comment]
Resolved.  We're opening a new work item to add this feature.  Expect the update available in mid Q4 2019. 
Suggest closing this issue.
