### ISSUE TITLE
Feature: Results page: add ability to sort sessions by date, status, label/tag (2018)

### ISSUE THREAD

**Issue by igor-borovkov** [cta-wave/WMAS#39]
Ability to sort test sessions by date, status (running etc), label/tag (when supported)

Note: discussed prior with Mark Vickers as a potential feature for WAVE test suite 2018

**Comment by louaybassbouss** [comment]
Sorting is not supported yet and it makes sense to support it in future releases of the test suite.

**Comment by mbergman42** [comment]
Resolved.  We're opening a new work item to add this feature.  Expect the update available in mid Q4 2019. 
Suggest closing this issue.
