### ISSUE TITLE
Feature: Results page: add labeling/tagging (2018)

### ISSUE THREAD

**Issue by igor-borovkov** [cta-wave/WMAS#41]
Ability to label / tag test sessions (similar to JIRA tickets labeling). 

Can be used to label test sessions with: 
- a build image name / release name
- a browser version tested (if the user agent string / test session token was generated on a desktop prior - in this case the user agent string is going to be incorrect)
- a device model name (when there are multiple devices on different architectures / platforms)

**Comment by mavgit** [comment]
FYI, I understand that a key purpose of this feature request is to enable the WAVE test suite to be integrated into and run by another test suite.

**Comment by louaybassbouss** [comment]
For now, the test sessions will be labeled with automatically with the UserAgent String of the Browser under test. Adding custom labels/tags is not supported yet but can be supported in future releases.

**Comment by mbergman42** [comment]
Resolved.  We're opening a new work item to add this feature.  Expect the update available in mid Q4 2019. 
Suggest closing this issue.
