### ISSUE TITLE
Feature: Report: add ability to see which assert failed / an assert message (2018)

### ISSUE THREAD

**Issue by igor-borovkov** [cta-wave/WMAS#42]
Include information that is otherwise available through a json report, a failed assert message. Maybe in some unobtrusive way (collapsed by default, or a highlight etc)

**Comment by louaybassbouss** [comment]
This needs to update the [wptreport](https://github.com/w3c/wptreport) to add this information in the HTML report. We already updated this tool (updated [wptreport](https://github.com/fraunhoferfokus/wptreport) ) to support advanced filtering in the HTML report and we can also extend it to support this feature.

**Comment by mbergman42** [comment]
Resolved.  We're opening a new work item to add this feature.  Expect the update available in mid Q4 2019. 
Suggest closing this issue.
