### ISSUE TITLE
Feature: Tests: ability to select HTML/media-elements as an independent item (2018)

### ISSUE THREAD

**Issue by igor-borovkov** [cta-wave/WMAS#43]
HTML category has a lot of tests, but only a small portion of them uses media data, specifically 
**/html/semantics/embedded-content/media-elements** which can be used for platform regression testing on a routine basis (after changes to Gstreamer libraries / plugins, changes to a platform SDK, drivers etc)

**Comment by louaybassbouss** [comment]
The API mentioned in #46 supports the selection of one or multiple paths. The UI supports for now only the high-level APIs (APIs root folder). Yes, it makes support fine granular selection as you proposed in the future.

**Comment by mbergman42** [comment]
Resolved.  We're opening a new work item to add this feature.  Expect the update available in mid Q4 2019. 
Suggest closing this issue.

**Comment by squapp** [comment]
this will be covered as part of #48
