### ISSUE TITLE
Feature: Results page: display date/time for each test session (2018)

### ISSUE THREAD

**Issue by igor-borovkov** [cta-wave/WMAS#44]
Add date/time column or the last time a particular session was used (in case when it's still running and when it's completed).  Sortable field (when sorting on the results page is supported)

**Comment by louaybassbouss** [comment]
The WMAS2018 test suite displays a date/time column as described. Sorting is not supported yet but agrees that it is a relevant feature request.

**Comment by squapp** [comment]
will be merged with feature request #39
