### ISSUE TITLE
Feature: Report: import/export reports (2018)

### ISSUE THREAD

**Issue by igor-borovkov** [cta-wave/WMAS#45]
Ability to import /export reports with a possibility to compare imported reports against each other and with "local" reports. 

Scenario 1: import a test report to a different CTA WAVE instance for comparison with test reports on that instance

Scenario 2: export a report generated for every major release of a web browser for backup reasons.

**Comment by louaybassbouss** [comment]
The new WMAS2018 test suite supports the export feature you mentioned. The import feature was not on our list but definitely relevant feature request as you described to allow comparison of test sessions on different instances of the Test Runner

**Comment by mbergman42** [comment]
Resolved.  We're opening a new work item to add this feature.  Expect the update available in mid Q4 2019. 
Suggest closing this issue.
