### ISSUE TITLE
API's required on WAVE platform to integrate with external systems.

### ISSUE THREAD

**Issue by vinaybhat83** [cta-wave/WMAS#48]
![image](https://user-images.githubusercontent.com/7661314/55755071-2520c700-5a1c-11e9-8a1e-7381b18520ee.png)

**Comment by mbergman42** [comment]
Resolved.  We're opening a new work item to add support equivalent to this feature request (note, not exactly as described above).  Expect the update available in mid Q4 2019. 
Suggest closing this issue.
