### ISSUE TITLE
Feature: Add code base version number to browser version number on landing page.

### ISSUE THREAD

**Issue by mavgit** [cta-wave/WMAS#49]
The current landing page has four buttons labeled with the reference browser name and version. For example, the 2017 tests show:

button 1 | button 2 | button 3 | button 4
-------- | -------- | -------- | --------
Edge 16 | Firefox 57 | Safari 10.13.1 | Chromium 63

By the way, I think the version number next to Safari is actually the Mac OS version number 10.13.1, which was released October 31, 2017. The Safari version in that release was 11.0.1, so the buttons should be:

button 1 | button 2 | button 3 | button 4
-------- | -------- | -------- | --------
Edge 16 | Firefox 57 | Safari 11.0.1 | Chromium 63

This is good, but device makers will often be building from the underlying open source code base, where applicable.

I propose we add the open source name and version number, where applicable, to both 2017 and 2018 landing page. The 2017 page would be:

button 1 | button 2 | button 3 | button 4
-------- | -------- | -------- | --------
Edge 16 | Firefox 57 | Safari 11.0.1 | Chromium 63
_ | Gecko 57 | WebKit 604.3.5? | Blink 537.36

Notes:
- Edge in 2017 has no open source base, so I labeled it "_", but should be blank.
- FireFox & Gecko version numbers are aligned, so that's easy!
- The WebKit number for Safari 11.0.1 may not be right.

The underlying code base version number should be found in the browser user agent string. My suggested 2017 version numbers should be checked against the user agent strings, particularly for Safari's WebKit, which may be wrong.

Other resources are:
- [Gecko versions](https://developer.mozilla.org/en-US/docs/Mozilla/Gecko/Versions)
- [Safari versions](https://en.wikipedia.org/wiki/Safari_version_history)
- [Chromium versions](https://en.wikipedia.org/wiki/Google_Chrome_version_history)

Since this is just adding three static version numbers to the landing pages, it should be a fairly minor fix.

**Comment by squapp** [comment]
this was added to the 2018 landing page: https://webapitests2018.ctawave.org
Will need to do the same for the 2017 landing page. Leaving the issue open until then

**Comment by FritzHeiden** [comment]
done.

WMATS 2017: 66403c2a564e13449820c6016bf9f1483c5a8399
WMATS 2018: f94774c810d35c24a354b39e392a5b750ee1993b
