### ISSUE TITLE
QR code feature on landing page to avoid navigation issues with remote control keys

### ISSUE THREAD

**Issue by squapp** [cta-wave/WMAS#56]
It was reported that on certain embedded devices there are problems with the autofocus when navigating using remote control keys.
We could avoid that by adding a QR code on the landing page and allow the user to configure the APIs and ref browsers to be tested on a second screen.

**Comment by mavgit** [comment]
Agree. I had this experience at NAB 2019 at a booth of a TV-browser company. Arrow keys didn't navigate as expected.

The QR code approach would address this and many other device UI issues.

**Comment by mbergman42** [comment]
Resolved.  We're opening a new work item to add this feature.  Expect the update available in mid Q4 2019. 
Suggest closing this issue.
