### ISSUE TITLE
test runner / deployment: launching test runner from broadcast - HbbTV

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/WMAS#62]
It would be good to have the ability to launch the WMAS (and DPCTF) test runner from broadcast signalling.
This issue is for HbbTV, ATSC3 is https://github.com/cta-wave/WMAS/issues/63.
This would be the following;
- Transport stream(s) pointing at the CTA cloud-hosted WMAS instance(s)
- The ability for a a locally hosted WMAS (and DPCTF) instance to generate a TS pointing at itself.

The TS will need to point at an HbbTV friendly landing page - see https://github.com/cta-wave/WMAS/issues/61 .

**Comment by jpiesing** [comment]
Other discussions about open source tools for creating HbbTV transport streams can be found here;
- https://github.com/cta-wave/dpctf-deploy/issues/1#issuecomment-770998016
- https://github.com/cta-wave/dpctf-deploy/issues/1#issuecomment-771048901

**Comment by JohnRiv** [comment]
@louaybassbouss will look into one TS for 2018, 2019 & 2020

**Comment by JohnRiv** [comment]
March 2nd HATF update - @louaybassbouss will have this available very soon

**Comment by louaybassbouss** [comment]
Is now available through this wiki page https://github.com/cta-wave/WMAS/wiki/HbbTV

**Comment by JohnRiv** [comment]
Closing for now as the documentation is available. If there are additional questions/issues, this (or another issue) can be reopened.
