### ISSUE TITLE
expired TLS server certificate for https://webapitests2019.ctawave.org/

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/WMAS#65]
The certificate has expired. An automatic update process would be preferred to a manual one.

![image](https://user-images.githubusercontent.com/8490792/118843583-7de50e00-b8ca-11eb-92b3-27197235aaff.png)

**Comment by louaybassbouss** [comment]
We will fix it the process is automatic but it seems there is an issue. we will take care of this and let you know

**Comment by JohnRiv** [comment]
https://webapitests2020.ctawave.org/ has an expired cert as well

**Comment by FritzHeiden** [comment]
Both domain's certificates are renewed and should work properly again

**Comment by louaybassbouss** [comment]
@jpiesing can we close this issue?

**Comment by jpiesing** [comment]
Both work now. 

@louaybassbouss @FritzHeiden Please confirm they will auto-renew in 3 months time & then close the issue.

**Comment by JohnRiv** [comment]
We'll leave this open for now and then close in 3 months to confirm it auto-renews

**Comment by JohnRiv** [comment]
I see the following updated certificate expiration dates:
* https://webapitests2019.ctawave.org/ -  Monday, November 8, 2021 at 10:33:51 AM Eastern Standard Time
* https://webapitests2020.ctawave.org/ -  Monday, November 8, 2021 at 10:34:12 AM Eastern Standard Time

As we agreed, I'll close this issue now that we see the auto-renewal has worked
