### ISSUE TITLE
Redirect /wave to /wave/

### ISSUE THREAD

**Issue by JohnRiv** [cta-wave/WMAS#67]
As Bob Campbell mentioned in #66, for usability purposes, it would be beneficial to have /wave redirect to /wave/ (or /wave/index.html) for the tests hosted at /wave/. 

Acceptance criteria for this would be:

- https://webapitests2018.ctawave.org/wave 301 redirects to https://webapitests2018.ctawave.org/wave/ (or https://webapitests2018.ctawave.org/wave/index.html)
- https://webapitests2019.ctawave.org/wave 301 redirects to https://webapitests2019.ctawave.org/wave/ (or https://webapitests2019.ctawave.org/wave/index.html)
- https://webapitests2020.ctawave.org/wave 301 redirects to https://webapitests2020.ctawave.org/wave/ (or https://webapitests2020.ctawave.org/wave/index.html)
- https://webapitests2021.ctawave.org/wave 301 redirects to https://webapitests2021.ctawave.org/wave/ (or https://webapitests2021.ctawave.org/wave/index.html)

**Comment by FritzHeiden** [comment]
This is now configured. Please check and let me know if anything is missing

**Comment by JohnRiv** [comment]
Looks good! Thanks @FritzHeiden!
