### ISSUE TITLE
Add test suite year to <h1> tag on /wave/

### ISSUE THREAD

**Issue by JohnRiv** [cta-wave/WMAS#68]
Not that we have multiple years of test suites available that all look the same on the main page, in order to easily know what test suite you're about to run, and especially since the 2021 URL has the 2020 tests hosted there for now, it would be useful to update the H1 tags to include the test suite year.

Acceptance criteria: 
- The `<h1>` tag for https://webapitests2018.ctawave.org/wave/ is **WAVE WMAS 2018 Test Suite**
- The `<h1>` tag for https://webapitests2019.ctawave.org/wave/ is **WAVE WMAS 2019 Test Suite**
- The `<h1>` tag for https://webapitests2020.ctawave.org/wave/ is **WAVE WMAS 2020 Test Suite**
- The `<h1>` tag for https://webapitests2021.ctawave.org/wave/ is **WAVE WMAS 2020 Test Suite** (for now, since the WMAS2020 test suite is deployed there, as WMAS2021 is still in development)

**Comment by FritzHeiden** [comment]
I changed the heading accordingly

**Comment by JohnRiv** [comment]
Looks good! Thanks @FritzHeiden!
