### ISSUE TITLE
ATSC Conformance Implementation Team would like more information on the scope of WMAS tests 

### ISSUE THREAD

**Issue by bobcampbell-eurofins** [cta-wave/WMAS#70]
Can WAVE share a list or spreadsheet of the WMAS (2019) tests from WAVE. This can aid in prioritizing WMAS tests for ATSC's scope.

Ideally, the list would be pre-filtered with only tests that we might consider - see also https://github.com/cta-wave/technical-working-group/issues/16 which ends with a proposal for how to streamline the set to something practical for TVs etc.

* ATSC A/344:2021 makes a normative reference to "CTA Specification: Web Application Video Ecosystem – Web Media API Snapshot
2019", Doc. CTA-5000-B, Consumer Technology Association, December 2019.

**Comment by louaybassbouss** [comment]
@bobcampbell-eurofins the attached zip file includes a list of all WMAS2019 tests. A snapshot of these tests is available in [wmas2019-tests](https://github.com/cta-wave/WMAS/tree/wmas2019-tests) branch. 

[wmas2019-tests.json.zip](https://github.com/cta-wave/WMAS/files/7971945/wmas2019-tests.json.zip)

**Comment by bobcampbell-eurofins** [comment]
Thanks, this item can be closed I believe
