### ISSUE TITLE
Non-Interactive Tests in WMAS 2020

### ISSUE THREAD

**Issue by javierbarellano4v** [cta-wave/WMAS#75]
Is there documentation/writeup or a way to filter and show or list tests that do NOT require user input on the DUT, i.e., where a set of tests will run until all completely done without user input on the DUT?

Thanks.

**Comment by javierbarellano4v** [comment]
A simple list of which tests require user input would suffice..., alternatively, I could step through each one separately and take note if interactive or not.

**Comment by FritzHeiden** [comment]
Tests that require interaction have "manual" in the filename. So under linux you could run something like 
```find . -type f -name "*.html" | grep "manual"``` in the WMAS directory to output all user interaction tests. Analogously, 
```find . -type f -name "*.html" | grep -v "manual"``` would output all non-user interaction tests. Run 
```find . -type f -name "*.html" | grep -v "manual" > automatic-tests.txt``` to output them into a file.

This is not quite accurate, as it will just look for html files, which are not necessarily test files. Only files that import the `testharness.js` are considered tests by the test runner.

**Comment by javierbarellano4v** [comment]
I'll take a look at this. Thanks @FritzHeiden

**Comment by javierbarellano4v** [comment]
going back to this.. where exactly do I execute this 'find', i.e., which directory?

**Comment by FritzHeiden** [comment]
In the root directory of the test runner. Alternatively, you can check out the respective tests branch, like the [wmas2020-tests](https://github.com/cta-wave/WMAS/tree/wmas2020-tests) branch and execute in that directory.

**Comment by JohnRiv** [comment]
In the November 9th HATF called, we agreed to close this. Thanks for your help @FritzHeiden @louaybassbouss
