### ISSUE TITLE
"502 Bad gateway" error on WMAS 2018 hosted version

### ISSUE THREAD

**Issue by bobcampbell-eurofins** [cta-wave/WMAS#76]
Hi following the link at https://github.com/cta-wave/WMAS/tree/wmas2018

"A hosted version is available at: https://webapitests2018.ctawave.org/" I get a "502 Bad Gateway" error?

(this is the version referenced by the current HbbTV 2.0.3 spec)

**Comment by FritzHeiden** [comment]
Thank you for reporting, the instance is back online

**Comment by JohnRiv** [comment]
Instance is still online, we are closing the issue. Thanks @FritzHeiden !
