### ISSUE TITLE
Unable to run test on WMAS 2019 and WMAS 2018 hosted version 

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/WMAS#77]
For both cloud hosted version of WMAS 2019 and WMAS 2018. 
https://webapitests2018.ctawave.org/wave/index.html
and https://webapitests2019.ctawave.org/wave/index.html

I am unable to run test. The test process stuck at the end of 1st test and does not load the next test. 
The result shows timedout:
{
    "results": [
        {
            "test": "/css/css-animations/animation-delay-001-manual.html",
            "status": "TIMEOUT",
            "message": null,
            "subtests": [
                {
                    "status": "TIMEOUT",
                    "xstatus": "SERVERTIMEOUT"
                }
            ]
        }
    ]
}

**Comment by louaybassbouss** [comment]
@yanj-github can you are running manual Test does this happen with automatic tests?

**Comment by yanj-github** [comment]
@louaybassbouss I think this only happens to the manual test. 
I was hoping it moves to next test after timeout but it didnt.

**Comment by louaybassbouss** [comment]
@yanj-github the manual tests can also disable the timeout of the test. I think this happens in this tests. PS: in WMAS we focus on automatic tests for manual tests there is no guarantee. Most manual tests expect keyboard or mouse for interaction which will not work on a TV set.

**Comment by yanj-github** [comment]
Thanks @louaybassbouss I can see there is a button for not including manual test which I can use for now. 
Can I ask if there an limitation on how many tests that I can put on "Excluded Tests" on configuration page please?
