### ISSUE TITLE
HbbTV friendly next.html

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/WMAS#82]
It seems that the following changes have not applied to the other versions.
https://github.com/cta-wave/WMAS/issues/61#issuecomment-1075386720
Can you help to apply same changes, add the hbbtv.js to next.html and added another query parameter "delay", to wmas2021 and wmas2018 please?

**Comment by FritzHeiden** [comment]
I added hbbtv.js and delay query parameter to next.html of all hosted versions.
