### ISSUE TITLE
Certificates have expired

### ISSUE THREAD

**Issue by JohnRiv** [cta-wave/WMAS#86]
These certs expired this morning:
- https://webapitests2018.ctawave.org/
- https://webapitests2019.ctawave.org/
- https://webapitests2020.ctawave.org/
- https://webapitests2021.ctawave.org/
- https://webapitests2022.ctawave.org/
- https://webapitests2023.ctawave.org/

https://webapitests2017.ctawave.org/ expires March 10th

**Comment by louaybassbouss** [comment]
@JohnRiv the issue is fixed. Feed free to close.

**Comment by JohnRiv** [comment]
Thanks Louay!
