### ISSUE TITLE
Question: manual tests or automated tests

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/WMAS#90]
Is there a way such as API call to find out a list of manual tests or automated tests?
Or is there a way to tell current running test is manual test please?

**Comment by louaybassbouss** [comment]
@yanj-github the WPT creates a large manifest JSON file (MANIFEST.json) the first time it is started. The manifest includes all the tests with metadata, where you can see if it is manual test or not. We can provide this file via API Call, but I don't recommend this option since it is too large.

**Comment by yanj-github** [comment]
Thanks @louaybassbouss, can we find out from HTML file name please? I can see "manual" from the HTML file name. Are they manual tests? Can other test does not contain "manual"  in the name can be manual test?

**Comment by louaybassbouss** [comment]
> Thanks @louaybassbouss, can we find out from HTML file name please? I can see "manual" from the HTML file name. Are they manual tests? Can other test does not contain "manual" in the name can be manual test?

yes exactly 👍

**Comment by yanj-github** [comment]
Thanks @louaybassbouss. Do you agree we can determine manual test from its name? 

- Tests contain "manual" are manual tests
- Tests does contain "manual" are automated tests
